"""Ollama LLM implementation for local models."""

import requests

from src.interfaces.llm_interface import LLM


class OllamaLLM(LLM):
    """LLM implementation using Ollama for local models."""

    def __init__(
        self,
        model: str = "llama3.2",
        base_url: str = "http://localhost:11434",
        temperature: float = 0.7,
    ):
        """
        Initialize Ollama LLM.

        Args:
            model: The Ollama model to use (e.g., 'llama3.2', 'mistral', 'gemma2').
            base_url: Ollama server URL.
            temperature: Sampling temperature.
        """
        self.model = model
        self.base_url = base_url
        self.temperature = temperature

    def generate(self, prompt: str) -> str:
        """
        Generate a response based on a given prompt.

        Args:
            prompt: The complete prompt to send to the LLM.

        Returns:
            The text response generated by the LLM.
        """
        system_prompt = (
            "You are a helpful assistant that answers questions based on the provided context. "
            "If the context doesn't contain relevant information, say so honestly."
        )

        response = requests.post(
            f"{self.base_url}/api/generate",
            json={
                "model": self.model,
                "prompt": prompt,
                "system": system_prompt,
                "stream": False,
                "options": {"temperature": self.temperature},
            },
            timeout=120,
        )
        response.raise_for_status()

        return response.json().get("response", "")
