"""OpenAI LLM implementation."""

from typing import Optional

from openai import OpenAI

from src.interfaces.llm_interface import LLM


class OpenAILLM(LLM):
    """LLM implementation using OpenAI API."""

    def __init__(
        self,
        model: str = "gpt-4o-mini",
        api_key: Optional[str] = None,
        temperature: float = 0.7,
        max_tokens: int = 2048,
    ):
        """
        Initialize OpenAI LLM.

        Args:
            model: The OpenAI model to use.
            api_key: OpenAI API key. If None, uses OPENAI_API_KEY env variable.
            temperature: Sampling temperature (0-2).
            max_tokens: Maximum tokens in response.
        """
        self.model = model
        self.temperature = temperature
        self.max_tokens = max_tokens
        self.client = OpenAI(api_key=api_key)

    def generate(self, prompt: str) -> str:
        """
        Generate a response based on a given prompt.

        Args:
            prompt: The complete prompt to send to the LLM.

        Returns:
            The text response generated by the LLM.
        """
        response = self.client.chat.completions.create(
            model=self.model,
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are a helpful assistant that answers questions "
                        "based on the provided context. "
                        "If the context doesn't contain relevant information, "
                        "say so honestly."
                    ),
                },
                {"role": "user", "content": prompt},
            ],
            temperature=self.temperature,
            max_tokens=self.max_tokens,
        )

        return response.choices[0].message.content or ""
