from abc import ABC, abstractmethod

class LLM(ABC):
    """An interface for Large Language Models."""

    @abstractmethod
    def generate(self, prompt: str) -> str:
        """
        Generate a response based on a given prompt.
        
        Args:
            prompt: The complete prompt to send to the LLM.
            
        Returns:
            The text response generated by the LLM.
        """
        pass
